services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: gonews-redis
    command: redis-server --requirepass Carloseduardo08#
    ports: 
      - "6379:6379"
    environment:
      - REDIS_ADDR=gonews-redis:6379
    networks:
      - app_network

  asynqmon:
    image: hibiken/asynqmon:latest
    ports:
      - 9090:9090
    entrypoint: ["./asynqmon", "--redis-addr=gonews-redis:6379"]
    networks:
     - app_network


  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go_news
    ports:
       - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
